export const FETCH_PREFECTURES_REQUESTED = "FETCH_PREFECTURES_REQUESTED";
export const FETCH_PREFECTURES_SUCCEEDED = "FETCH_PREFECTURES_SUCCEEDED";
export const FETCH_PREFECTURES_FAILED = "FETCH_PREFECTURES_FAILED";

export const PREFECTURE_SELECTED = "PREFECTURE_SELECTED";

export const FETCH_CITIES_BY_PREFECTURE_ID_REQUESTED =
  "FETCH_CITIES_BY_PREFECTURE_ID_REQUESTED";
export const FETCH_CITIES_BY_PREFECTURE_ID_SUCCEEDED =
  "FETCH_CITIES_BY_PREFECTURE_ID_SUCCEEDED";
export const FETCH_CITIES_BY_PREFECTURE_ID_FAILED =
  "FETCH_CITIES_BY_PREFECTURE_ID_FAILED";

export const CITY_SELECTED = "CITY_SELECTED";

export const FETCH_CITY_BY_ID_REQUESTED = "FETCH_CITY_BY_ID_REQUESTED";
export const FETCH_CITY_BY_ID_SUCCEEDED = "FETCH_CITY_BY_ID_SUCCEEDED";
export const FETCH_CITY_BY_ID_FAILED = "FETCH_CITY_BY_ID_FAILED";
