export const FETCH_PREFECTURES_REQUESTED = "FETCH_PREFECTURES_REQUESTED";
export const FETCH_PREFECTURES_SUCCEEDED = "FETCH_PREFECTURES_SUCCEEDED";
export const FETCH_PREFECTURES_FAILED = "FETCH_PREFECTURES_FAILED";

export const PREFECTURE_SELECTED = "PREFECTURE_SELECTED";

export const FETCH_CITIES_BY_PREFECTURE_ID_REQUESTED =
  "FETCH_CITIES_BY_PREFECTURE_ID_REQUESTED";
export const FETCH_CITIES_BY_PREFECTURE_ID_SUCCEEDED =
  "FETCH_CITIES_BY_PREFECTURE_ID_SUCCEEDED";
export const FETCH_CITIES_BY_PREFECTURE_ID_FAILED =
  "FETCH_CITIES_BY_PREFECTURE_ID_FAILED";

export const CITY_SELECTED = "CITY_SELECTED";

export const FETCH_CITY_BY_ID_REQUESTED = "FETCH_CITY_BY_ID_REQUESTED";
export const FETCH_CITY_BY_ID_SUCCEEDED = "FETCH_CITY_BY_ID_SUCCEEDED";
export const FETCH_CITY_BY_ID_FAILED = "FETCH_CITY_BY_ID_FAILED";

export const OPEN_RULES_MODAL_BUTTON_CLICKED =
  "OPEN_RULES_MODAL_BUTTON_CLICKED";
export const CLOSE_RULES_MODAL_BUTTON_CLICKED =
  "CLOSE_RULES_MODAL_BUTTON_CLICKED";

export const FEEDBACK_FORM_VALUES_UPDATED = "FEEDBACK_FORM_VALUES_UPDATED";
export const POST_FEEDBACK_FORM_REQUESTED = "POST_FEEDBACK_FORM_REQUESTED";
export const POST_FEEDBACK_FORM_SUCCEEDED = "POST_FEEDBACK_FORM_SUCEEDED";
export const POST_FEEDBACK_FORM_FAILED = "POST_FEEDBACK_FORM_FAILED";
export const OPEN_FEEDBACK_FORM_BUTTON_CLICKED =
  "OPEN_FEEDBACK_FORM_BUTTON_CLICKED";
export const CANCEL_RETRY_POST_BUTTON_CLICKED =
  "CANCEL_RETRY_POST_BUTTON_CLICKED";
export const ENABLE_EMAIL_FORM_FIELD_TOGGLED =
  "ENABLE_EMAIL_FORM_FIELD_TOGGLED";
