export const FETCH_CITIES_REQUESTED = "FETCH_CITIES_REQUESTED";
export const FETCH_CITIES_SUCCEEDED = "FETCH_CITIES_SUCCEEDED";
export const FETCH_CITIES_FAILED = "FETCH_CITIES_FAILED";

export const FETCH_PREFECTURES_REQUESTED = "FETCH_PREFECTURES_REQUESTED";
export const FETCH_PREFECTURES_SUCCEEDED = "FETCH_PREFECTURES_SUCCEEDED";
export const FETCH_PREFECTURES_FAILED = "FETCH_PREFECTURES_FAILED";

export const PREFECTURE_SELECTED = "PREFECTURE_SELECTED";

export const FETCH_CITIES_BY_PREFECTURE_ID_REQUESTED =
  "FETCH_CITIES_BY_PREFECTURE_ID_REQUESTED";
export const FETCH_CITIES_BY_PREFECTURE_ID_SUCCEEDED =
  "FETCH_CITIES_BY_PREFECTURE_ID_SUCCEEDED";
export const FETCH_CITIES_BY_PREFECTURE_ID_FAILED =
  "FETCH_CITIES_BY_PREFECTURE_ID_FAILED";
